[package]
name = "fl-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = { version = "0.34.1", default-features = false, features = ["macros", "libm"] }

[features]
default = []
std = ["nalgebra/std"]
